//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoCentre.Resources.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Client {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Client() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcoCentre.Resources.Model.Client", typeof(Client).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seulement les utilisateurs actifs.
        /// </summary>
        public static string ActiveOnly {
            get {
                return ResourceManager.GetString("ActiveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter client.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client avec cette adresse existe déjà.
        /// </summary>
        public static string AddressExists {
            get {
                return ResourceManager.GetString("AddressExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse existe déjà dans la base de données..
        /// </summary>
        public static string AddressExistsOrCreationNotAllowed {
            get {
                return ResourceManager.GetString("AddressExistsOrCreationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte client.
        /// </summary>
        public static string AllowClientCreditCheckbox {
            get {
                return ResourceManager.GetString("AllowClientCreditCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº appartement.
        /// </summary>
        public static string AptNumber {
            get {
                return ResourceManager.GetString("AptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commerce.
        /// </summary>
        public static string CategoryCommerce {
            get {
                return ResourceManager.GetString("CategoryCommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string CategoryInstitution {
            get {
                return ResourceManager.GetString("CategoryInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipalité.
        /// </summary>
        public static string CategoryMunicipality {
            get {
                return ResourceManager.GetString("CategoryMunicipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la catégorie.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBNL.
        /// </summary>
        public static string CategoryOBNL {
            get {
                return ResourceManager.GetString("CategoryOBNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string CategoryOther {
            get {
                return ResourceManager.GetString("CategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résident.
        /// </summary>
        public static string CategoryResident {
            get {
                return ResourceManager.GetString("CategoryResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte Citoyen.
        /// </summary>
        public static string CitizenCard {
            get {
                return ResourceManager.GetString("CitizenCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string CityOther {
            get {
                return ResourceManager.GetString("CityOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº civique.
        /// </summary>
        public static string CivicNumber {
            get {
                return ResourceManager.GetString("CivicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro du compte.
        /// </summary>
        public static string ClientCreditAcountNumber {
            get {
                return ResourceManager.GetString("ClientCreditAcountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaires.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clé unique.
        /// </summary>
        public static string ExternalId {
            get {
                return ResourceManager.GetString("ExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre.
        /// </summary>
        public static string FilterClientsLabel {
            get {
                return ResourceManager.GetString("FilterClientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom du client.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regroupement.
        /// </summary>
        public static string Hub {
            get {
                return ResourceManager.GetString("Hub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville invalide.
        /// </summary>
        public static string InvalidCity {
            get {
                return ResourceManager.GetString("InvalidCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro du compte. Le format correct est 1234567-89.
        /// </summary>
        public static string InvalidCreditAccountFormat {
            get {
                return ResourceManager.GetString("InvalidCreditAccountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postal invalide. Le format correct est ANA-NAN.
        /// </summary>
        public static string InvalidPostalCodeFormat {
            get {
                return ResourceManager.GetString("InvalidPostalCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du client.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBNL dernière visite.
        /// </summary>
        public static string LastOBNLVisit {
            get {
                return ResourceManager.GetString("LastOBNLVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellulaire.
        /// </summary>
        public static string MobilePhoneNumber {
            get {
                return ResourceManager.GetString("MobilePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la Municipalité.
        /// </summary>
        public static string MunicipalityName {
            get {
                return ResourceManager.GetString("MunicipalityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du client.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string NameOfOrganization {
            get {
                return ResourceManager.GetString("NameOfOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Ville&apos; must be specified.
        /// </summary>
        public static string NewCityNameMustBeSpecified {
            get {
                return ResourceManager.GetString("NewCityNameMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non vérifié.
        /// </summary>
        public static string NoVerified {
            get {
                return ResourceManager.GetString("NoVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de nombre de visites.
        /// </summary>
        public static string NumberOfVisitsLimit {
            get {
                return ResourceManager.GetString("NumberOfVisitsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de OBNL visites.
        /// </summary>
        public static string NumOBNLVisits {
            get {
                return ResourceManager.GetString("NumOBNLVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de visites.
        /// </summary>
        public static string NumVisits {
            get {
                return ResourceManager.GetString("NumVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro ORG.
        /// </summary>
        public static string OBNLNumber {
            get {
                return ResourceManager.GetString("OBNLNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro ORG.
        /// </summary>
        public static string OBNLNumbers {
            get {
                return ResourceManager.GetString("OBNLNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite des visites personnelles.
        /// </summary>
        public static string PersonalVisitsLimit {
            get {
                return ResourceManager.GetString("PersonalVisitsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite des visites personnelles ne peut être modifiée par l&apos;administrateur mondiale.
        /// </summary>
        public static string PersonalVisitsLimitChangeAccessDenied {
            get {
                return ResourceManager.GetString("PersonalVisitsLimitChangeAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de téléphone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postale.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___-___-____.
        /// </summary>
        public static string PostalCodePlaceholder {
            get {
                return ResourceManager.GetString("PostalCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;enregistrement.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le client.
        /// </summary>
        public static string SelectClient {
            get {
                return ResourceManager.GetString("SelectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seulement actif.
        /// </summary>
        public static string ShowActiveOnly {
            get {
                return ResourceManager.GetString("ShowActiveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de filtre.
        /// </summary>
        public static string ShowEveryone {
            get {
                return ResourceManager.GetString("ShowEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seulement supprimé.
        /// </summary>
        public static string ShowInactiveOnly {
            get {
                return ResourceManager.GetString("ShowInactiveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif.
        /// </summary>
        public static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactif.
        /// </summary>
        public static string StatusInactive {
            get {
                return ResourceManager.GetString("StatusInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rue.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifié.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
    }
}
