//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoCentre.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Forms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcoCentre.Resources.Forms", typeof(Forms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rétablir.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter des adresses à fusionner.
        /// </summary>
        public static string AddMergeSource {
            get {
                return ResourceManager.GetString("AddMergeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoriser nouvelle adresse.
        /// </summary>
        public static string AllowAddressCreation {
            get {
                return ResourceManager.GetString("AllowAddressCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer l&apos;adresse de fusion.
        /// </summary>
        public static string ChangeMergeDest {
            get {
                return ResourceManager.GetString("ChangeMergeDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone / Courriel.
        /// </summary>
        public static string ClientContactDetailsMissingMsg {
            get {
                return ResourceManager.GetString("ClientContactDetailsMissingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations incomplètes.
        /// </summary>
        public static string ClientContactDetailsTag {
            get {
                return ResourceManager.GetString("ClientContactDetailsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche client.
        /// </summary>
        public static string ClientSearch {
            get {
                return ResourceManager.GetString("ClientSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste de clients.
        /// </summary>
        public static string ClientsList {
            get {
                return ResourceManager.GetString("ClientsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients fusion.
        /// </summary>
        public static string ClientsMerger {
            get {
                return ResourceManager.GetString("ClientsMerger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non vérifiés.
        /// </summary>
        public static string ClientUnverified {
            get {
                return ResourceManager.GetString("ClientUnverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renseignements sur les clients ont été importés et doivent être vérifiées..
        /// </summary>
        public static string ClientVefiryClientDetailsMsg {
            get {
                return ResourceManager.GetString("ClientVefiryClientDetailsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string DashboardTotal {
            get {
                return ResourceManager.GetString("DashboardTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;écocentre.
        /// </summary>
        public static string EcocenterName {
            get {
                return ResourceManager.GetString("EcocenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éditer.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Client.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des factures exclus.
        /// </summary>
        public static string ExcludedInvoicesList {
            get {
                return ResourceManager.GetString("ExcludedInvoicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite globale du nombre de visites.
        /// </summary>
        public static string GlobalLimitOfNumberOfVisits {
            get {
                return ResourceManager.GetString("GlobalLimitOfNumberOfVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aller à la page:.
        /// </summary>
        public static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des factures inclus.
        /// </summary>
        public static string IncludedInvoicesList {
            get {
                return ResourceManager.GetString("IncludedInvoicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des factures.
        /// </summary>
        public static string InvoiceList {
            get {
                return ResourceManager.GetString("InvoiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle facture.
        /// </summary>
        public static string InvoiceNew {
            get {
                return ResourceManager.GetString("InvoiceNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Années précédentes.
        /// </summary>
        public static string InvoicePreviousYears {
            get {
                return ResourceManager.GetString("InvoicePreviousYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;opération est irréversible! Assurez-vous de vérifier soigneusement l&apos;entrée!.
        /// </summary>
        public static string Irreversible {
            get {
                return ResourceManager.GetString("Irreversible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles par page.
        /// </summary>
        public static string ItemsPerPage {
            get {
                return ResourceManager.GetString("ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapports de longues périodes de temps pourrait prendre beaucoup de temps pour terminer!.
        /// </summary>
        public static string LongPeriodReportsWarning {
            get {
                return ResourceManager.GetString("LongPeriodReportsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matériaux.
        /// </summary>
        public static string MaterialsList {
            get {
                return ResourceManager.GetString("MaterialsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matériaux fusion.
        /// </summary>
        public static string MaterialsMerger {
            get {
                return ResourceManager.GetString("MaterialsMerger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle facture ne peut pas être créé. Le client a atteint ou dépassé le nombre maximum de visites:.
        /// </summary>
        public static string MaxVisitsReachedMsg {
            get {
                return ResourceManager.GetString("MaxVisitsReachedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de visites.
        /// </summary>
        public static string MaxVisitsReachedTag {
            get {
                return ResourceManager.GetString("MaxVisitsReachedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention le client a atteint le nombre de visite suivant:.
        /// </summary>
        public static string MaxVisitsWarningMsg {
            get {
                return ResourceManager.GetString("MaxVisitsWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de visites.
        /// </summary>
        public static string MaxVisitsWarningTag {
            get {
                return ResourceManager.GetString("MaxVisitsWarningTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusionner.
        /// </summary>
        public static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fusionner clients.
        /// </summary>
        public static string MergeClients {
            get {
                return ResourceManager.GetString("MergeClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse de destination après la fusion.
        /// </summary>
        public static string MergeDest {
            get {
                return ResourceManager.GetString("MergeDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La destination de la fusion est l&apos;adresse où toutes les adresses sélectionnées seront fusionnés. Ce sera la seule adresse restant après la fusion et toutes les factures seront fusionnés ici..
        /// </summary>
        public static string MergeDestDescription {
            get {
                return ResourceManager.GetString("MergeDestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fusionner matériaux.
        /// </summary>
        public static string MergeMaterials {
            get {
                return ResourceManager.GetString("MergeMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les adresses sélectionnées seront fusionnées à l&apos;adresse de destination, et ils seront supprimés après la fusion..
        /// </summary>
        public static string MergeSorceDescription {
            get {
                return ResourceManager.GetString("MergeSorceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresses à fusionner.
        /// </summary>
        public static string MergeSource {
            get {
                return ResourceManager.GetString("MergeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau Client.
        /// </summary>
        public static string NewClient {
            get {
                return ResourceManager.GetString("NewClient", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Nouveau Client.
		/// </summary>
		public static string NewCanadianClient
		{
			get
			{
				return ResourceManager.GetString("NewCanadianClient", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		public static string OnlyActive {
            get {
                return ResourceManager.GetString("OnlyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de courrier de l&apos;utilisateur a été configuré. S&apos;il vous plaît contacter l&apos;administrateur..
        /// </summary>
        public static string PasswordResetNoEmailConfigured {
            get {
                return ResourceManager.GetString("PasswordResetNoEmailConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur avec un nom d&apos;utilisateur ou mot de passe donné n&apos;a pas été trouvé..
        /// </summary>
        public static string PasswordResetNoUserFound {
            get {
                return ResourceManager.GetString("PasswordResetNoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur est nécessaire.
        /// </summary>
        public static string PasswordResetUsernameIsRequired {
            get {
                return ResourceManager.GetString("PasswordResetUsernameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prévisualiser.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seulement le matériel CRD peut être accepté.
        /// </summary>
        public static string RegisteredInAnotherHubMsg {
            get {
                return ResourceManager.GetString("RegisteredInAnotherHubMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre regroupement.
        /// </summary>
        public static string RegisteredInAnotherHubTag {
            get {
                return ResourceManager.GetString("RegisteredInAnotherHubTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauver.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse de destination de la fusion.
        /// </summary>
        public static string SelectedMergeDest {
            get {
                return ResourceManager.GetString("SelectedMergeDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez les adresses à fusionner.
        /// </summary>
        public static string SelectedMergeSources {
            get {
                return ResourceManager.GetString("SelectedMergeSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez la destination de fusion.
        /// </summary>
        public static string SelectMergeDest {
            get {
                return ResourceManager.GetString("SelectMergeDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les clients sans visites.
        /// </summary>
        public static string ShowClientsWithNoVisits {
            get {
                return ResourceManager.GetString("ShowClientsWithNoVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher uniquement les clients avec le limite de visites  plus élevé que le limite globale.
        /// </summary>
        public static string ShowOnlyPersonalVisitsHigherThanGlobalClients {
            get {
                return ResourceManager.GetString("ShowOnlyPersonalVisitsHigherThanGlobalClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # de visites.
        /// </summary>
        public static string TotalVisits {
            get {
                return ResourceManager.GetString("TotalVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poids Totale par OBNL.
        /// </summary>
        public static string TotalWeight {
            get {
                return ResourceManager.GetString("TotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non vérifiées.
        /// </summary>
        public static string Unverified {
            get {
                return ResourceManager.GetString("Unverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client a été importé automatiquement. S&apos;il vous plaît vérifier les informations du client en allant dans &apos;Éditer&apos; page..
        /// </summary>
        public static string UnverifiedTooltip {
            get {
                return ResourceManager.GetString("UnverifiedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des utilisateurs.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreurs de validation.
        /// </summary>
        public static string ValidationErrors {
            get {
                return ResourceManager.GetString("ValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
